### ISSUE TITLE
{NameError}name 'uses_learning_phase' is not defined

### ISSUE THREAD

**Issue by valendin** [digantamisra98/Mish#13]
When using in an RNN, I get ```{NameError}name 'uses_learning_phase' is not defined``` when applying a Dense layer on the output of an LSTM.

Tensorflow 1.14

**Comment by digantamisra98** [comment]
Hi. Can you please provide the code so that I can replicate the error you're receiving along with the log. I haven't used Mish as of now on a LSTM so I'll have to check to validate the same. Meanwhile, I'm referring to these issue forums here: 
1. https://github.com/tensorflow/tensorflow/issues/23425
2. https://github.com/keras-team/keras/issues/4178

**Comment by digantamisra98** [comment]
@valendin can you try using Mish from the Tensorflow Addons repository. Implementation is given here - https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations

**Comment by valendin** [comment]
@digantamisra98 will do, have just moved to TF 2.0 so will have to retest

**Comment by qo4on** [comment]
> using Mish from the Tensorflow Addons repository. Implementation is given here - https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations

There is no `mish` activation:
```
dir(tfa.activations)
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'division',
 'gelu',
 'hardshrink',
 'lisht',
 'print_function',
 'sparsemax',
 'tanhshrink']
```
How can I import it to TF 2.0?

**Comment by digantamisra98** [comment]
@qo4on have you updated TFA? Because Mish is here - https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/mish.py

**Comment by qo4on** [comment]
I installed latest tfa in Colab:
```
!pip install tensorflow-addons
import tensorflow_addons as tfa
```
Maybe I should have used nightly build `!pip install tfa-nightly` but I didn't find how to import it after the installation. I never used `tfa` before. Do you know how can I import `tfa-nightly`?

**Comment by digantamisra98** [comment]
@qo4on I just noticed that they're yet to put out their next release which is why Mish isn't a part of the package even though it's up on the source. You can directly install from the source (Instruction on their Readme) or else wait for the release for this month. I'll put forth an inquiry on when the next release is coming. Thanks

**Comment by digantamisra98** [comment]
@qo4on here's the update - https://github.com/tensorflow/addons/issues/683#issuecomment-551346829

**Comment by qo4on** [comment]
Eventually I found the way to use Mish from the Tensorflow Addons in Colab:
```python
!pip install tf-nightly==2.1.0.dev20191029
!pip install tfa-nightly
import tensorflow_addons as tfa
dir(tfa.activations)
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'division',
 'gelu',
 'hardshrink',
 'lisht',
 'mish',
 'print_function',
 'rrelu',
 'softshrink',
 'sparsemax',
 'tanhshrink']
```

**Comment by digantamisra98** [comment]
@qo4on Good to know. Let me know if there is any other issues regarding Mish. 
@valendin closing this issue as of now, I believe using Mish from TFA will solve the error. Feel free to re-open it if the issue persists. Thanks!
