### ISSUE TITLE
TF-Keras module name

### ISSUE THREAD

**Issue by mehmetalianil** [digantamisra98/Mish#17]
I know that it is minor, but it would ease things out to rename the folder TF-Keras.
Then we can just git clone repo & import.

Otherwise python doesn't like dashes in module/package names.

**Comment by digantamisra98** [comment]
Thanks for pointing that out. I have changed the folder name. Commit - [32d83f560b6b](https://github.com/digantamisra98/Mish/commit/be440ba12e7b4a37113e530a179e32d83f560b6b)
If you're using Native TF then I would suggest to try the TensorFlow Addons Implementation. 
Closing the issue.

**Comment by mehmetalianil** [comment]
Yep, trying that now, but I think it requires nightly.

**Comment by digantamisra98** [comment]
@mehmetalianil Please refer to this issue thread on how to import Mish from TFA - https://github.com/tensorflow/addons/issues/683#issuecomment-552015320
As of now yes it requires the dev-nightly but TFA is planning to have the next release pretty soon, the delay is because of the migration to TF 2.0.
